name: Lint, Format & UT (Frontend)

on:
  pull_request:
    branches:
      - dev
    types: [opened, reopened, synchronize]
    paths:
      - 'frontend/**'
      - '.github/workflows/1_PR-dev-frontend.yaml'

jobs:  
  check-lint-run-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Setup dependencies
        run: npm install

      - name: Run lint check
        run: npm run check-lint

      - name: Run unit tests
        run: npm run unit-tests
