name: Run all tests

on:
  pull_request:
    branches:
      - staging

jobs:
  test-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend
          # - upload
          # - chat
          # - ...
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./${{ matrix.service }}

      - name: Run Unit Tests (${{ matrix.service }})
        run: npm run unit-tests
        working-directory: ./${{ matrix.service }}

      - name: Run Integration Tests (${{ matrix.service }})
        run: npm run integration-tests
        working-directory: ./${{ matrix.service }}

  test-e2e:
    runs-on: ubuntu-latest
    needs: test-services

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Run E2E Tests
        run: |
          docker compose -f compose.e2e.yaml up --build --abort-on-container-exit
          docker compose -f compose.e2e.yaml down